# Generated by Django 4.1.1 on 2022-09-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Basliq')),
                ('content', models.TextField(verbose_name='Xeber')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('draft', models.BooleanField(default=True, verbose_name='publish')),
            ],
            options={
                'verbose_name': 'Xeber',
                'verbose_name_plural': 'Xeberler',
            },
        ),
    ]
