# Generated by Django 4.1.1 on 2022-09-27 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id'], 'verbose_name': 'Xeber', 'verbose_name_plural': 'Xeberler'},
        ),
    ]
